app/frontend/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from .views import HomepageView, RoomsListView, RoomDetailView, DiscoverListView, ContactView, AboutUsView, DiscoverDetailGrView
from .views_eng import HomepageEngView, RoomsListEngView, RoomDetailEngView, DiscoverListEngView, ContactEngView, AboutUsEngView, DiscoverDetailEngView
from .footer_views import TermOfUseView, TermOfUseEngView, PrivacyCookiesEngView, PrivacyCookiesView
from .ajax_views import show_ajax_modal_gr_view, show_ajax_modal_eng_view

from .sitemaps import StaticViewsSitemap
from rooms.sitemap import RoomSitemap
from discover.sitemap import DiscoverCategorySitemap


sitemaps = {
    'static': StaticViewsSitemap,
    'rooms': RoomSitemap,

}

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage_gr'),
    path('διαμονη/', RoomsListView.as_view(), name='room_list_gr'),
    path('η-ιστορια-μας/', AboutUsView.as_view(), name='about_us_gr'),
    path('τα-δωματια-μας/δωματιο/<slug:slug>/', RoomDetailView.as_view(), name='room_detail_gr'),
    path('προορισμοί/', DiscoverListView.as_view(), name='discover_list_gr'),
    url(r'^προορισμός/(?P<slug>[-\w]+)/$',  DiscoverDetailGrView.as_view(), name='discover_detail_view'),
    path('επικοινωνια/', ContactView.as_view(), name='contact_gr'),
    path('όροι-χρήσης/', TermOfUseView.as_view(), name='term_of_use_gr'),
    path('προσωπικά-δεδομένα-cookies/', PrivacyCookiesView.as_view(), name='privacy_gr'),


    path('eng/', HomepageEngView.as_view(), name='homepage_eng'),
    path('eng/our-story/', AboutUsEngView.as_view(), name='about_us_eng'),
    path('eng/rooms/', RoomsListEngView.as_view(), name='room_list_eng'),
    path('eng/rooms/room/<slug:slug>/', RoomDetailEngView.as_view(), name='room_detail_eng'),
    path('eng/discover/', DiscoverListEngView.as_view(), name='discover_list_eng'),
    url(r'^eng/discover/details/(?P<slug>[-\w]+)/$', DiscoverDetailEngView.as_view(), name='discover_detail_eng'),
    path('eng/contact/', ContactEngView.as_view(), name='contact_eng'),

    path('eng/term-of-use/', TermOfUseEngView.as_view(), name='term_of_use_eng'),
    path('eng/personal-data/', PrivacyCookiesEngView.as_view(), name='privacy_eng'),

    # ajax views
    url(r'ajax/show-modal-discover/(?P<slug>[-\w]+)/$', show_ajax_modal_gr_view, name='show_discover_modal_gr'),
    url(r'eng/ajax/show-discover/(?P<slug>[-\w]+)/$', show_ajax_modal_eng_view, name='show_discover_modal_eng'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),



]

app/gregory_aparments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.conf import settings
from frontend.views import favicon_img_view

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('frontend.urls')),
    path('newslettters/', include('newsletter.urls')),

    path('favicon.ico', favicon_view)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.error_404_page'

app/newsletter/urls.py
from django.urls import path


from .views import form_valid_newsletter_form_view, form_valid_newsletter_form_view_eng, newsletter_page_view


app_name = 'newsletter'

urlpatterns = [
    path('newsletter/validate-form/', form_valid_newsletter_form_view, name='newsletter_valid_form'),
    path('eng/newsletter/validate-form/', form_valid_newsletter_form_view_eng, name='newsletter_valid_form_eng'),
    path('newsletter/<slug:slug>/', newsletter_page_view, name='newsletter_page_view'),

]

app/newsletter/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.urls import reverse_lazy

from tinymce.models import HTMLField


class NewsLetterPage(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(unique=True, max_length=200, verbose_name='ΤΙΤΛΟΣ ΣΤΑ ΕΛΛΗΝΙΚΑ')
    slug = models.SlugField(blank=True)
    image = models.ImageField(upload_to='news_letter_images')
    text = HTMLField(null=True, verbose_name='ΚΕΙΜΕΝΟ ΣΤΑ ΕΛΛΗΝΙΚΑ')

    title_eng = models.CharField(unique=True, max_length=200, verbose_name='ΤΙΤΛΟΣ ΣΤΑ ΑΓΓΛΙΚΑ')
    text_eng = HTMLField(null=True, verbose_name='ΚΕΙΜΕΝΟ ΣΤΑ ΑΓΓΛΙΚΑ')

    def __str__(self):
        return self.title

    def my_url(self):
        return reverse_lazy('newsletter:newsletter_page_view', kwargs={'slug': self.slug})


class NewsLetter(models.Model):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    cell_phone = models.CharField(max_length=200, blank=True)
    acceptRules = models.BooleanField(default=False)
    newsletterPage = models.ForeignKey(NewsLetterPage, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.email





@receiver(post_save, sender=NewsLetterPage)
def create_slug_signal(sender, instance, **kwargs):
    slug = instance.slug
    if not slug:
        new_slug = slugify(instance.title, allow_unicode=True)
        qs_exists = NewsLetterPage.objects.filter(slug=new_slug).exists()
        instance.slug = f'{new_slug}-{instance.id}' if qs_exists else new_slug
        instance.save()

app/newsletter/forms.py
from django import forms

from .models import NewsLetter


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NewsLetterForm(BaseForm, forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'width': '50%'}))
    acceptRules = forms.BooleanField(required=True, label='Αποδέχομαι τους όρους χρήσης')

    class Meta:
        model = NewsLetter
        fields = ['email', 'acceptRules']


class NewsLetterFormEng(BaseForm, forms.ModelForm):
    # email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'width:50%'}))
    acceptRules = forms.BooleanField(required=True, label='Accept the terms of Use')

    class Meta:
        model = NewsLetter
        fields = ['email', 'acceptRules']

app/newsletter/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib import messages
# Create your views here.

from .forms import NewsLetterForm
from .models import NewsLetterPage


def form_valid_newsletter_form_view(request):
    form = NewsLetterForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        messages.success(request, f'Το {obj.email} καταχωρήθηκε. Ευχαριστούμε!')
    else:
        messages.success(request, f'Το email που χρησιμοποιείται υπάρχει ήδη στην λίστα μας. Ευχαριστούμε!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def form_valid_newsletter_form_view_eng(request):
    form = NewsLetterForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        messages.success(request, f'{obj.email} is added to our list. Thank You!')
    else:
        messages.success(request, f'The email which used is already added to our list. Thank You!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def newsletter_page_view(request, slug):
    obj = get_object_or_404(NewsLetterPage, slug=slug)
    if not obj.active:
        return HttpResponseRedirect('/')
    form = NewsLetterForm()
    return render(request, 'newsletter/page.html', context={'obj': obj, 'form': form})

app/newsletter/templates/newsletter/page.html
{% extends 'index.html' %} {% load static %}

{% block extra_css %}
    <style>

        .image_div {
            background: url({% static 'my_images/diamoni.jpg' %}) no-repeat center center fixed;
              -webkit-background-size: cover;
              -moz-background-size: cover;
              -o-background-size: cover;
              background-size: cover;
              height: 100%;
              width: 100%;
        }
        #id_email {



        }
        p, label{
            color: white;
        }

    </style>
{% endblock %}

{% block content %}
    <div role="main" class="main image_div" >
        <div class="custom-page-wrapper pt-5 ">
            <div class="spacer py-4 my-5">
                <div class="row">
                    <div class="col-md-12 align-self-center p-static text-center">
						<div class="overflow-hidden mb-2">
							<h1 class="text-12 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="1200">
								{{ page_title }}
							</h1>
						</div>
					</div>
                    {% comment %}
					<div class="col-md-12 align-self-center">
						<div class="overflow-hidden">
							<ul class="custom-breadcrumb-style-1 breadcrumb breadcrumb-light custom-font-secondary d-block text-center custom-ls-1 text-5 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="1450">
								<li class="text-transform-none"><a style="color: black;" href="{% url 'homepage_gr' %}" class="text-decoration-none">ΑΡΧΙΚΗ ΣΕΛΙΔΑ</a></li>
								<li style="color: black;" class="text-transform-none active"> {{ page_title }}</li>
							</ul>
						</div>
					</div>
					{% endcomment %}
				</div>
            </div>

        </div>
        <div class="custom-page-wrapper pt-5 pb-1">
            <div class="spacer py-4 my-5"></div>
            <div class="container container-lg-custom" >
                <div class="row">
                    <div class="col-2 "></div>
                    <div class="col-md-8 col-sm-12">
                        <div class="card">
                            <div class="card-header text-center">
                                <h4>Ο Διαγωνισμός μας <br />
                                    {{ obj.title }} </h4>
                            </div>
                            <div class="card-body " style="background-color: #CAAF97">
                                <form method="post" class="form text-center" action="{% url 'newsletter:newsletter_valid_form' %}">
                                    {{ form }}
                                    <hr />
                                    <button type="submit" class="btn btn-info" style="background-color: white;color: #CAAF97">  ΕΓΓΡΑΦΗ </button>
                                    <br />
                                    <hr>
                                    <h5>ΠληροφορΙες Διαγωνισμου</h5>

                                    <a target="_blank" style="color: white"  href="{% url 'privacy_gr' %}">¨Οροι Χρήσης</a>
                                </form>

                                {{ obj.text|safe }}

                                <hr />
                            </div>
                        </div>
                    </div>
                     <div class="col-2"></div>

                </div>
                <div class="row" style="margin-bottom: 200px"></div>
            </div>


            </div>
        </div>
    </div>
{% endblock %}


{% block footer %} {% endblock %}