app/frontend/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from .views import HomepageView, RoomsListView, RoomDetailView, DiscoverListView, ContactView, AboutUsView, DiscoverDetailGrView
from .views_eng import HomepageEngView, RoomsListEngView, RoomDetailEngView, DiscoverListEngView, ContactEngView, AboutUsEngView, DiscoverDetailEngView
from .footer_views import TermOfUseView, TermOfUseEngView, PrivacyCookiesEngView, PrivacyCookiesView
from .ajax_views import show_ajax_modal_gr_view, show_ajax_modal_eng_view

from .sitemaps import StaticViewsSitemap
from rooms.sitemap import RoomSitemap
from discover.sitemap import DiscoverCategorySitemap


sitemaps = {
    'static': StaticViewsSitemap,
    'rooms': RoomSitemap,

}

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage_gr'),
    path('διαμονη/', RoomsListView.as_view(), name='room_list_gr'),
    path('η-ιστορια-μας/', AboutUsView.as_view(), name='about_us_gr'),
    path('τα-δωματια-μας/δωματιο/<slug:slug>/', RoomDetailView.as_view(), name='room_detail_gr'),
    path('προορισμοί/', DiscoverListView.as_view(), name='discover_list_gr'),
    url(r'^προορισμός/(?P<slug>[-\w]+)/$',  DiscoverDetailGrView.as_view(), name='discover_detail_view'),
    path('επικοινωνια/', ContactView.as_view(), name='contact_gr'),
    path('όροι-χρήσης/', TermOfUseView.as_view(), name='term_of_use_gr'),
    path('προσωπικά-δεδομένα-cookies/', PrivacyCookiesView.as_view(), name='privacy_gr'),


    path('eng/', HomepageEngView.as_view(), name='homepage_eng'),
    path('eng/our-story/', AboutUsEngView.as_view(), name='about_us_eng'),
    path('eng/rooms/', RoomsListEngView.as_view(), name='room_list_eng'),
    path('eng/rooms/room/<slug:slug>/', RoomDetailEngView.as_view(), name='room_detail_eng'),
    path('eng/discover/', DiscoverListEngView.as_view(), name='discover_list_eng'),
    url(r'^eng/discover/details/(?P<slug>[-\w]+)/$', DiscoverDetailEngView.as_view(), name='discover_detail_eng'),
    path('eng/contact/', ContactEngView.as_view(), name='contact_eng'),

    path('eng/term-of-use/', TermOfUseEngView.as_view(), name='term_of_use_eng'),
    path('eng/personal-data/', PrivacyCookiesEngView.as_view(), name='privacy_eng'),

    # ajax views
    url(r'ajax/show-modal-discover/(?P<slug>[-\w]+)/$', show_ajax_modal_gr_view, name='show_discover_modal_gr'),
    url(r'eng/ajax/show-discover/(?P<slug>[-\w]+)/$', show_ajax_modal_eng_view, name='show_discover_modal_eng'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),



]

app/gregory_aparments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.conf import settings
from frontend.views import favicon_img_view

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('frontend.urls')),
    path('newslettters/', include('newsletter.urls')),

    path('favicon.ico', favicon_view)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.error_404_page'

app/newsletter/urls.py
from django.urls import path


from .views import form_valid_newsletter_form_view, form_valid_newsletter_form_view_eng, newsletter_page_view


app_name = 'newsletter'

urlpatterns = [
    path('newsletter/validate-form/', form_valid_newsletter_form_view, name='newsletter_valid_form'),
    path('eng/newsletter/validate-form/', form_valid_newsletter_form_view_eng, name='newsletter_valid_form_eng'),
    path('newsletter/<slug:slug>/', newsletter_page_view, name='newsletter_page_view'),

]

app/frontend/models.py
from django.db import models
from django.core.mail import send_mail
from tinymce.models import HTMLField
from django.conf import settings

from .managers import BannerManager
# Create your models here.

SITE_EMAIL = settings.SITE_EMAIL


class Instagram(models.Model):
    active = models.BooleanField(default=True)
    url = models.TextField(null=True)

    def __str__(self):
        return f'Instagram Photo {self.id}'


class Banner(models.Model):
    SIZE_TYPE = (
        ('1', 'ΒΑΣΙΚΟ ΑΡΙΣΤΕΡΑ => (845*815)'),
        ('b', 'ΒΑΣΙΚΟ ΔΕΞΙΑ => (845*815)'),
        ('2', 'Second Banner'),
        ('3', 'About Page')
    )
    active = models.BooleanField(default=True, verbose_name='ΚΑΤΑΣΤΑΣΗ')
    category = models.CharField(default='1', max_length=1, choices=SIZE_TYPE, verbose_name='ΚΑΤΗΓΟΡΙΑ')
    image = models.ImageField(upload_to='banners/', verbose_name='ΕΙΚΟΝΑ')
    title = models.CharField(max_length=240, null=True, blank=True)
    objects = models.Manager()
    my_query = BannerManager()

    def __str__(self):
        return f'Image {self.id}'


class Contact(models.Model):
    CATEGORY_TYPES = (
        ('a', 'Γενική Ερώτηση - General question'),
        ('b', 'Κρατήσεις - Booking Info'),
    )
    email = models.EmailField()
    category = models.CharField(max_length=1, choices=CATEGORY_TYPES, null=True, verbose_name='Κατηγορία')
    title = models.CharField(max_length=200, verbose_name='Θέμα')
    name = models.CharField(max_length=200, verbose_name='Ονοματεπώνυμο', null=True, blank=True)
    phone = models.CharField(max_length=15, blank=True, verbose_name='Τηλέφωνο')
    text = HTMLField(verbose_name='Μήνυμα')
    is_readed = models.BooleanField(default=False, verbose_name='ΔΙΑΒΑΣΜΕΝΟ')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['is_readed', ]

    def __str__(self):
        return self.title

    @staticmethod
    def send_email(form, gr=True):
        message = form.cleaned_data.get('title', None)
        email = form.cleaned_data.get('email', None)
        title = 'Σας ευχαριστούμε για την ερώτηση, θα σας απαντήσουμε το συντομότερο δυνατόν' if gr\
            else 'Thank you for the question, we will inform you shortly'
        send_mail(
            title,
            message,
            SITE_EMAIL,
            [email, ],
            fail_silently=True
        )

    @staticmethod
    def inform_admin_email(form):
        title = f'{form.cleaned_data.get("title", " No Title")} | {form.cleaned_data.get("category", "No Category")}'
        message = form.cleaned_data.get('text', None)
        email = form.cleaned_data.get('email', None)
        send_mail(
            title,
            f'{email} | {message}',
            SITE_EMAIL,
            [SITE_EMAIL, ],
            fail_silently=True

        )

app/rooms/models.py
from django.db import models
from django.shortcuts import reverse
from tinymce.models import HTMLField


def upload_photo(instance, filename):
    return f'photos/{instance.room.title}/{filename}'

def extra_upload_photo(instance, filename):
    return f'photos/{instance.id}/{filename}'

class Room(models.Model):
    BED_OPTIONS = (
        ('1', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ'),
        ('2', 'ΜΟΝΟ ΚΡΕΒΑΤΙ'),
        ('3', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ-ΚΑΝΑΠΕΣ ΚΡΕΒΑΤΙ'),
        ('4', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ ΚΑΙ 2 ΜΟΝΑ ΚΡΕΒΑΤΙΑ')


    )
    BED_OPTIONS_ENG = (
        ('1', '1 DOUBLE BED'),
        ('2', 'SINGLE BED'),
        ('3', '1 DOUBLE BED -SOFA BED'),
        ('4', '1 DOUBLE DED AND 2 SINGLE BEDS')
    )
    active = models.BooleanField(default=True, verbose_name='ΚΑΤΑΣΤΑΣΗ')
    title = models.CharField(max_length=200, unique=True, verbose_name='ΤΙΤΛΟΣ')
    description = HTMLField(blank=True, verbose_name='ΠΕΡΙΓΡΑΦΗ')
    room_size = models.IntegerField(blank=True, verbose_name='ΜΕΓΕΘΟΣ ΔΩΜΑΤΙΟΥ')
    bed_size = models.CharField(default='1', max_length=1, choices=BED_OPTIONS, verbose_name='ΠΕΡΙΓΡΑΦΗ ΚΡΕΒΑΤΙΩΝ')
    maximum_people = models.IntegerField(default=1, verbose_name='ΜΕΓΙΣΤΗ ΧΩΡΗΤΙΚΟΤΗΤΑ')
    maximum_little_people = models.IntegerField(default=0, verbose_name='ΠΑΙΔΙΑ')

    # english fields
    title_eng = models.CharField(unique=True, max_length=200, verbose_name='ΤΙΤΛΟΣ ENG', null=True)
    description_eng = HTMLField(blank=True, verbose_name='ΠΕΡΙΓΡΑΦΗ ENG')
    bed_size_eng = models.CharField(max_length=1, default='1', choices=BED_OPTIONS_ENG, verbose_name='ΠΕΡΙΓΡΑΦΗ ΚΡΕΒΑΤΙΩΝ ENG')
    webatelier_link = models.URLField(blank=True,)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True, max_length=240, db_index=True)
    location = models.TextField(blank=True, null=True)
    extra_image = models.ImageField(blank=True, null=True, upload_to=extra_upload_photo)
    extra_text_gr = HTMLField(null=True, blank=True)
    extra_text_eng = HTMLField(null=True, blank=True)
    extra = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'ΔΩΜΑΤΙΑ'
        verbose_name = 'ΔΩΜΑΤΙΟ'

    def __str__(self):
        return self.title

    def image(self):
        qs = self.images.filter(is_primary=True)
        return qs.first().image if qs.exists() else None

    def my_images(self):
        return self.images.filter(is_primary=False)

    def get_absolute_url(self):
        return reverse('room_detail_gr', kwargs={'slug': self.slug})

    def get_absolute_url_eng(self):
        return reverse('room_detail_eng', kwargs={'slug': self.slug})


class Characteristic(models.Model):
    title = models.CharField(max_length=220, verbose_name='ΤΙΤΛΟΣ', null=True)
    title_eng = models.CharField(max_length=220, verbose_name='ΤΙΤΛΟΣ', null=True)
    rooms = models.ManyToManyField(Room, null=True, verbose_name='ΔΩΜΑΤΙΟ', related_name='chars')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'ΧΑΡΑΚΤΗΡΙΣΤΙΚΑ ΠΡΟΪΌΝΤΟΣ'
        verbose_name = 'ΧΑΡΑΚΤΗΡΙΣΤΙΚΟ'


class Photo(models.Model):
    is_primary = models.BooleanField(default=False, verbose_name='ΒΑΣΙΚΗ PHOTO')
    image = models.ImageField(upload_to=upload_photo, verbose_name='PHOTO', help_text='445*445')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return f'{self.room}- {self.id}'

app/frontend/forms.py
from django import forms

from .models import Contact

CATEGORY_TYPES_ENG = (
        ('a', 'General question'),
        ('b', 'Booking Info'),
    )


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ContactForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['email', 'title', 'name', 'phone', 'text']


class ContactFormEng(BaseForm, forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['email', 'title',  'phone', 'text']
        labels = {
            'title': 'Title',
            'phone': 'Phone',
            'text': 'Message',
            'name': 'Name'
        }

app/frontend/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.contrib import messages
from django.http import HttpResponse
from .forms import ContactForm
from .models import Banner, Contact, Instagram
from rooms.models import Room
from discover.models import Discover


class HomepageView(TemplateView):
    template_name = 'gr/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data(**kwargs)
        context['page_title'] = 'Αρχική Σελίδα'
        context['banners'] = Banner.objects.filter(active=True)
        context['rooms'] = Room.objects.filter(active=True)
        context['eng_link'] = reverse('homepage_eng')
        context['discovers'] = Discover.objects.filter(active=True, is_favorite=True)[:3]
        return context


class AboutUsView(TemplateView):
    template_name = 'gr/aboutus_view.html'

    def get_context_data(self, **kwargs):
        context = super(AboutUsView, self).get_context_data(**kwargs)
        context['page_title'] = 'Ποιοι Είμαστε'
        context['eng_link'] = reverse('about_us_eng')
        context['photos'] = Banner.my_query.get_active().filter()
        return context


class RoomsListView(ListView):
    queryset = Room.objects.filter(active=True)
    model = Room
    template_name = 'gr/room_list_view.html'

    def get_context_data(self,  **kwargs):
        context = super(RoomsListView, self).get_context_data(**kwargs)
        context['page_title'] = 'Τα δωμάτια μας'
        context['eng_link'] = reverse('room_list_eng')

        return context


class RoomDetailView(DetailView):
    queryset = Room.objects.filter(active=True)
    model = Room
    template_name = 'gr/room_detail_view.html'

    def get_context_data(self, **kwargs):
        context = super(RoomDetailView, self).get_context_data(**kwargs)
        context['page_title'] = self.object.title
        # context['keywords'] = ''
        context['eng_link'] = self.object.get_absolute_url_eng
        return context


class DiscoverListView(ListView):
    queryset = Discover.objects.filter(active=True)
    model = Discover
    template_name = 'gr/discover_list_view.html'

    def get_context_data(self,  **kwargs):
        context = super(DiscoverListView, self).get_context_data(**kwargs)
        context['page_title'] = 'Κοντινοί Προορισμοί'
        context['eng_link'] = reverse('discover_list_eng')
        return context


class DiscoverDetailGrView(DetailView):
    queryset = Discover.objects.filter(active=True)
    model = Discover
    template_name = 'gr/discover_detail_view.html'

    def get_context_data(self, **kwargs):
        context = super(DiscoverDetailGrView, self).get_context_data(**kwargs)
        context['page_title'] = self.object.title
        context['eng_link'] = self.object.get_absolute_eng_url()
        return context


class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'gr/contact.html'
    success_url = reverse_lazy('contact_gr')

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['eng_link'] = reverse('contact_eng')
        context['page_title'] = 'Επικοινωνία'
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Η ερώτηση σας καταχωρήθηκε επιτυχώς')
        Contact.send_email(form)
        Contact.inform_admin_email(form)
        return super(ContactView, self).form_valid(form)


def error_404_page(request, exception):
    return render(request, '404_error.html')
    # response.status_code = 404
    # return response


def favicon_img_view(request):
    image_data = open('favicon.ico').read()
    return HttpResponse(image_data, content_type='ico')

app/frontend/templates/eng/discover_detail_view.html
{% extends 'eng/index.html' %}

{% block content %}

{% endblock %}

app/frontend/templates/eng/index.html
<!DOCTYPE html> {% load static %}
<html lang="zxx">

<head>
    {% include  'include/head.html' %}
     {% block extra_cs %} {% endblock %}
    <!-- page title -->
    <title>  Menexes | {{ page_title }}</title>
</head>

<body>
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <!-- Modal -->
                    <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Message</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            {{ message }}
                          </div>

                        </div>
                      </div>
                    </div>
            {% endfor %}
        </ul>
{% endif %}
{% block content %}
    <!-- page wrapper -->
    <div class="knsl-app">
            {% include 'include/navbar_eng.html' %}

            <!-- datepicker frame -->
            <div class="knsl-datepicker-place"></div>

            <!-- banner -->
            <section class="knsl-banner">
                      <div class="knsl-cover-frame">
                        <img src="{% static 'my_photos/test_1.jpg' %}" alt="banner" class="knsl-parallax">
                      </div>
                      <div class="knsl-overlay"></div>

                      <div class="knsl-banner-content">
                        <div class="container">
                          <div class="knsl-main-title">
                            <div class="knsl-white">
                              <!-- main-title -->
                              <h1 class="knsl-center knsl-mb-10">Welcome to Menexes</h1>
                              <div class="knsl-mb-30 knsl-center">You can find us in Monemvasia Kastro</div>
                            </div>
                          </div>
                            {% comment %}
                          <div class="knsl-book-form knsl-book-form-2">
                            <form>
                              <div class="row align-items-center">
                                <div class="col-12 col-lg-3">
                                  <div class="knsl-input-frame knsl-book-form-2">
                                    <label for="check-in">Check in</label>
                                    <input id="check-in" type="text" class="datepicker-here" data-position="bottom left" placeholder="Select date" autocomplete="off" readonly="readonly">
                                  </div>
                                </div>
                                <div class="col-12 col-lg-3">
                                  <div class="knsl-input-frame">
                                    <label for="check-out" class="knsl-add-icon">Check out</label>
                                    <input id="check-out" type="text" class="datepicker-here" data-position="bottom left" placeholder="Select date" autocomplete="off" readonly="readonly">
                                  </div>
                                </div>
                                <div class="col-6 col-lg-3">
                                  <div class="knsl-select-frame">
                                    <label for="person">Person</label>
                                    <select id="person">
                                      <option value="1">1</option>
                                      <option value="2">2</option>
                                      <option value="3">3</option>
                                      <option value="4" disabled>4</option>
                                    </select>
                                  </div>
                                </div>
                                <div class="col-6 col-lg-2">
                                  <div class="knsl-select-frame">
                                    <label for="children">Childrens</label>
                                    <select id="children">
                                      <option value="1">1</option>
                                      <option value="2">2</option>
                                      <option value="3">3</option>
                                      <option value="4" disabled>4</option>
                                    </select>
                                  </div>
                                </div>
                                <div class="col-12 col-lg-1 text-center">
                                  <button type="submit" class="knsl-btn"><img src="{% static 'img/icons/search.svg' %}" class="knsl-zoom" alt="icon"><span>Serch room</span></button>
                                </div>
                              </div>
                            </form>
                          </div>
                            {% endcomment %}
                        </div>
                      </div>
                    </section>
            <!-- banner end -->

            <!-- features -->
            <section id="knsl-triger-1">

              <div class="container">

                <!-- features card -->
                <div class="knsl-features-card" style="margin-top: -80px;">

                   <div class="row">
                    <div class="col-6 col-lg-6">

                      <!-- icon box -->
                      <div class="knsl-icon-box">
                          <i class="fa fa-phone fa-3x"></i>
                        <a href="tel:6976800433"> <h6 style="margin-top: 1%">Phones:
                          6939899187 - 6976800433</h6> </a>
                      </div>
                      <!-- icon box end -->

                    </div>
                    <div class="col-6 col-lg-6">

                      <!-- icon box -->
                      <div class="knsl-icon-box">
                          <i class="fa fa-mail-bulk fa-3x"></i>
                          <a href="mailto:xrysman@gmail.com"><h6 style="margin-top: 1%">EMAIL: xrysman@gmail.com</h6></a>
                      </div>
                      <!-- icon box end -->

                    </div>

                </div>
                <!-- features card end -->

              </div>
            </section>
            <!-- features end -->

            <!-- about -->
            <section class="knsl-p-100-100">

              <div class="container">
                <div class="knsl-about-card">
                  <div class="row no-gutters">
                    <div class="col-lg-6">
                      <div class="knsl-about-photo">
                        <img src="{% static 'my_photos/about_us.jpg' %}" alt="cover">
                      </div>
                    </div>
                    <div class="col-lg-6 align-self-center">
                      <div class="knsl-about-text">
                        <div class="knsl-title-frame">
                          <h2 class="knsl-mb-20">About us</h2>
                          <p class="knsl-mb-30">
                            In beautiful Monemvasia, a true love<br>
                            He comes to us from the old days, much to teach us<br>
                            They adorn our beautiful history with grace<br>
                            Fiorelli and Melica our beautiful couple<br>
                            Where the kitapias wrote their love in the castle<br>
                            And it kindled and covered the highest palaces<br>
                            We will also drink malvasia amber at their weddings
                            My beautiful Monemvasia, the pride of the world<br>
                          </p>
                          <a href="{% url 'about_us_eng' %}" class="knsl-btn knsl-btn-md">Learn more..</a>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 order-lg-2">
                      <div class="knsl-about-photo">
                        <img src="{% static 'my_photos/destinations.jpg' %}" alt="cover">
                      </div>
                    </div>
                    <div class="col-lg-6 align-self-center">
                      <div class="knsl-about-text">
                        <div class="knsl-title-frame">
                          <h2 class="knsl-mb-20">Destinations</h2>
                          <p class="knsl-mb-30">The Castle City of Monemvasia is not a destination, it is an experience.
                              That's why we gathered some of the best destinations to experience it.</p>
                          <a href="{% url 'discover_list_eng' %}" class="knsl-btn knsl-btn-md">Learn more...</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </section>
            <!-- about end -->


            <!-- rooms -->
            <section class="knsl-transition-bottom" style="background-color: #ECFAFB">
              <img src="{% static 'img/palm.svg' %}" class="knsl-deco-left" alt="palm">
              <div class="container">
                <div class="row align-items-center">
                  <div class="col-lg-12">

                    <div class="knsl-center knsl-title-frame knsl-scroll-animation knsl-mb-100">
                      <h2 class="knsl-mb-20">Rooms</h2>
                      <p class="knsl-mb-30">Consectetur adipisicing elit. Nihil, illum voluptate eveniet ex fugit ea delectus, sed voluptatem. Laborum accusantium libero commodi id officiis itaque esse adipisci, necessitatibus asperiores, illo odio.</p>
                      <a href="{% url 'room_list_eng' %}" class="knsl-btn knsl-btn-md">More</a>
                    </div>

                  </div>
                  <div class="col-lg-12">
                    <div class="swiper-container knsl-uni-slider">
                      <div class="swiper-wrapper">
                          {% for room in rooms %}
                              <div class="swiper-slide">{% include 'include/room_card_eng.html' %}</div>
                          {% endfor %}
                      </div>
                    </div>

                      <!-- slider navigation -->
                      <div class="knsl-uni-slider-nav-panel">
                        <div class="knsl-uni-slider-pagination"></div>
                        <div class="knsl-uni-nav">
                          <div class="knsl-uni-slider-prev"><i class="fas fa-arrow-left"></i></div>
                          <div class="knsl-uni-slider-next"><i class="fas fa-arrow-right"></i></div>
                        </div>
                      </div>
                      <!-- slider navigation end -->
                  </div>
                </div>
              </div>
            </section>
            <!-- rooms end -->

            <!-- services -->
            <section class="knsl-p-100-80">
              <div class="container">
                <div class="row">
                  <div class="col-lg-12">

                    <div class="knsl-center knsl-title-frame knsl-scroll-animation knsl-mb-100">
                      <h2 class="knsl-mb-20">Destinations</h2>
                      <p class="knsl-mb-30"></p>
                      <a href="{% url 'discover_list_eng' %}" class="knsl-btn knsl-btn-md">More</a>
                    </div>

                  </div>
                    {% for ele in discovers %}
                        <div class="col-lg-4">
                            {% include 'include/destination_card_eng.html' %}
                        </div>
                    {% endfor %}

                </div>
              </div>
            </section>
            <!-- services end -->


            <!-- blog -->
            <section class="knsl-p-0-80" style="background-color: #ECFAFB">
              <img src="{% static 'img/palm.svg' %}" class="knsl-deco-right" alt="palm">
              <div class="container">
                <div class="row">
                    <div class="col-3"></div>
                  <div class="col-lg-6">

                    <div class="knsl-center knsl-title-frame knsl-scroll-animation knsl-mb-100">
                      <h2 class="knsl-mb-20">Our Newsletter</h2>
                      <p class="knsl-mb-30">Learn first our news!</p>
                        <form method="post" class="form" action="{% url 'newsletter:newsletter_valid_form_eng' %}">
                            {% csrf_token  %}
                            <input name="email" type="email" placeholder="Email.." class="form-control" required>
                            <button type="submit" class="btn-success btn">Subscribe </button>
                        </form>
                    </div>

                  </div>

                </div>
              </div>
            </section>
            <!-- blog end -->






          </div>
          <!-- page wrapper end -->

  {% endblock %}
{% include 'include/footer_eng.html' %}
{% include 'include/js.html' %}
</body>



</html>

app/frontend/templates/eng/room_list_view.html
{% extends 'eng/index.html' %} {% load  static %}

{% block content %}

    <!-- page wrapper -->
    <div class="knsl-app">
    {% include 'include/navbar_eng.html' %}
       <!-- banner -->
    <section class="knsl-banner-simple knsl-transition-bottom">
      <img src="{% static 'img/palm.svg' %}" class="knsl-deco-left" alt="palm">
      <img src="{% static 'img/palm.svg' %}" class="knsl-deco-right" alt="palm">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">

            <div class="knsl-center knsl-title-frame">
              <h1 class="knsl-mb-20 knsl-h1-inner">Rooms</h1>
              <p class="knsl-mb-30"></p>
              <ul class="knsl-breadcrumbs">
                <li><a href="{% url 'homepage_eng' %}">Homepage</a></li>
                <li><span>Rooms</span></li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!-- banner end -->

    <!-- rooms -->
    <section class="knsl-p-100-100">
      <img src="{% static 'img/palm.svg' %}" class="knsl-deco-left" alt="palm">
      <div class="container">

          {% comment %}
            <div class="knsl-filter knsl-mb-60">
              <a href="#" data-filter="*" class="knsl-work-category knsl-current">All Rooms</a>
              <a href="#" data-filter=".economy" class="knsl-work-category">Economy</a>
              <a href="#" data-filter=".standart" class="knsl-work-category">Standart</a>
              <a href="#" data-filter=".deluxe" class="knsl-work-category">Deluxe</a>
            </div>
        {% endcomment %}

        <div class="knsl-masonry-grid knsl-3-col">


          <div class="knsl-grid-sizer"></div>
          <div class="col-lg-12">
            <div class="swiper-container knsl-uni-slider">
              <div class="swiper-wrapper">
                  {% for room in room_list %}
                      <div class="swiper-slide">{% include 'include/room_card_eng.html' %}</div>
                  {% endfor %}
              </div>
            </div>
        
        </div>

      </div>
      </div>
    </section>
    <!-- rooms end -->


  </div>
    <!-- page wrapper end -->

{% endblock %}